<?php 
/*
Plugin Name:       Dismiss Server Nag
Plugin URI:        https://github.com/luciano-croce/dismiss-server-nag/
Description:       Dismiss coming soon dashboard "<strong>Server Happy</strong>" nag, when is activated, or automatically, if it is in mu-plugins directory.
Version:           1.0.0
Requires at least: 2.3
Tested up to:      5.0
Requires PHP:      5.2.4
Author:            Luciano Croce
Author URI:        https://github.com/luciano-croce/
License:           GPLv2 or later
License URI:       https://www.gnu.org/licenses/gpl-2.0.html
Text Domain:       dismiss-server-nag
Domain Path:       /languages
Network:           true
GitHub Plugin URI: https://github.com/luciano-croce/dismiss-server-nag/
GitHub Branch:     master
Requires WP:       2.3
 *
 * Warning: to avoid code corruption, do not edit this file with WordPress embedded editor,
 * or with an editor not compatible UTF-8 without BOM Unix LF
 *
 * Copyright 2018 Luciano Croce (email: luciano.croce@gmail.com)
 *
 * According to the terms of the GNU General Public License, part of Copyright belongs to its own author,
 * and part belongs to other respective their authors, if exist.
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU
 * General Public License version 2, as published by the Free Software Foundation. You may NOT assume
 * that you can use any other compatible version of the GPL, or version compatible with GPL.
 *
 * This program is distributed in the hope that it will be useful, on an "AS IS", but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This program is written with the intent of being helpful,
 * but you are responsible for its use or actions on your own website.
 *
 * According to the terms of the Detailed Plugin Guidelines (wordpress.org) in particular:
 * - This developer(s) are responsible(s) for the contents and actions of this plugin.
 * - Stable version of this plugin is only available from the WordPress Plugin Directory page.
 * - Plugin version numbers is be incremented for each new release.
 * - Complete plugin was be available on GitHub before the time of submission.
 * - This plugin respect trademarks, copyrights, and project names.
 *
 * Tips - A neat trick, is to put this single file dismiss-server-nag.php (not its parent directory)
 * in the /wp-content/mu-plugins/ directory (create it if not exists) so you won't even have to enable it,
 * and will be loaded by default, also, since first step installation of WordPress setup!
 *
 * Translation - All readable text of this plugin are code free,
 * no HTML tags was inserted (showed) on Text Domain strings of GlotPress.
 *
 * The code of this plugin is not written with a php framework, but with a simple php editor, manually.
 */

	/**
	 * Dismiss Server Nag
	 *
	 * Dismiss automatically update nagging on dashboard, admin menu, and admin tool bar.
	 *
	 * PHPDocumentor
	 *
	 * @package    WordPress\Plugin
	 * @subpackage Dashboard\Dismiss_Server_Nag
	 * @link       https://wordpress.org/plugins/dismiss-server-nag/
	 * @version    1.0.1 (Build 2018-01-10) Stable
	 * @since      1.0.0 (Build 2018-01-10) 1st Release
	 * @author     Luciano Croce <luciano.croce@gmail.com>
	 * @copyright  2013-2018 - Luciano Croce
	 * @license    https://www.gnu.org/licenses/gpl-2.0.html - GPLv2 or later
	 * @todo       Preemptive support for WordPress 5.0-alpha
	 */

/**
 * Prevent direct access to plugin files.
 *
 * For security reasons, exit without any notifications:
 * - without show the details of the system
 * - without warn the existence of this plugin
 * - show the generic header 403 forbidden error
 * - close the connection header
 *
 * @author  Luciano Croce <luciano.croce@gmail.com>
 * @version 1.0.1 (Build 2018-01-10)
 * @since   1.0.0 (Build 2018-01-10)
 */
if ( ! defined( 'ABSPATH' ) ) exit;
if ( ! defined(  'WPINC'  ) ) exit;

if ( ! function_exists( 'add_action' ) ) {
	header( 'HTTP/0.9 403 Forbidden' );
	header( 'HTTP/1.0 403 Forbidden' );
	header( 'HTTP/1.1 403 Forbidden' );
	header( 'HTTP/2.0 403 Forbidden' );
	header( 'Status:  403 Forbidden' );
	header( 'Connection: Close'      );
		exit;
}

	global $wp_version;
	include( ABSPATH . WPINC . '/version.php' );
	$version = str_replace( '-src', '', $wp_version );

	add_filter( 'plugins_loaded', 'ddwcun_load_plugin_textdomain' );
	if ( version_compare( $version, '3.0', '>=' ) ) {
		add_filter( 'plugins_loaded', 'ddwcun_load_muplugin_textdomain' );
	}
	add_filter( 'admin_init',                            'dismiss_dashboard_widget_server_happy_nag' ); # 4.9+ to 5.0-alpha ~ draft
	add_filter( 'admin_init',                             'remove_dashboard_widget_server_happy_nag' ); # 4.9+ to 5.0-alpha ~ draft

	/**
	 * Load Plugin Textdomain
	 *
	 * @author  Luciano Croce <luciano.croce@gmail.com>
	 * @version 1.0.1 (Build 2018-01-10)
	 * @since   1.0.0 (Build 2018-01-10)
	 */
	function ddwcun_load_plugin_textdomain() {
		load_plugin_textdomain( 'dismiss-server-nag', false, basename( dirname( __FILE__ ) ) . '/languages' );
	}

	/**
	 * Load MU-Plugin (dir) Textdomain
	 *
	 * @author  Luciano Croce <luciano.croce@gmail.com>
	 * @version 1.0.1 (Build 2018-01-10)
	 * @since   1.0.0 (Build 2018-01-10)
	 */
	function ddwcun_load_muplugin_textdomain() {
		load_muplugin_textdomain( 'dismiss-server-nag', basename( dirname( __FILE__ ) ) . '/languages' );
	}

	/**
	* Dismiss Dashboard Widget Server Happy Nag
	*
	* @author  Luciano Croce <luciano.croce@gmail.com>
	* @version 1.0.1 (Build 2017-11-18)
	* @since   1.0.0 (Build 2018-01-10)
	*/
	function dismiss_dashboard_widget_server_happy_nag() {
		global $wp_meta_boxes;
		unset($wp_meta_boxes['dashboard']['normal']['high']['dashboard_server_nag']);      # draft
		unset($wp_meta_boxes['dashboard']['normal']['high']['dashboard_serverhappy_nag']); # draft
	}

	/**
	* Remove Dashboard Widget Server Happy Nag - ddwbun
	*
	* This, is different from the other similar plugins, because uses the filter hook, and not the action hook.
	*
	* Filters should filter information, thus receiving information/data, applying the filter and returning information/data,
	* and then used. However, filters are still action hooks. WordPress defines add_filter/remove_filter as "hooks a function
	* to a specific filter action", and add_action/remove_action as "hooks a function on to a specific action".
	*
	* @author  Luciano Croce <luciano.croce@gmail.com>
	* @version 1.0.1 (Build 2017-11-18)
	* @since   1.0.0 (Build 2018-01-10)
	*/
	function remove_dashboard_widget_server_happy_nag() {
		remove_filter( 'server_panel',           'wp_server_panel' ); # draft
		remove_filter( 'serverhappy_panel', 'wp_serverhappy_panel' ); # draft
	}
